// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2025-09-25T21:36:43.505Z

import type { FiletypeParserOptions } from "./types"

import javascript_highlights from "./assets/javascript/highlights.scm" with { type: "file" }
import javascript_language from "./assets/javascript/tree-sitter-javascript.wasm" with { type: "file" }
import typescript_highlights from "./assets/typescript/highlights.scm" with { type: "file" }
import typescript_language from "./assets/typescript/tree-sitter-typescript.wasm" with { type: "file" }

export const DEFAULT_PARSERS: FiletypeParserOptions[] = [
  {
    filetype: "javascript",
    queries: {
      highlights: [javascript_highlights],
    },
    language: javascript_language,
  },
  {
    filetype: "typescript",
    queries: {
      highlights: [typescript_highlights],
    },
    language: typescript_language,
  },
]
