// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2025-09-30T23:05:12.134Z

import type { FiletypeParserOptions } from "./types"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

import javascript_highlights from "./assets/javascript/highlights.scm" with { type: "file" }
import javascript_language from "./assets/javascript/tree-sitter-javascript.wasm" with { type: "file" }
import typescript_highlights from "./assets/typescript/highlights.scm" with { type: "file" }
import typescript_language from "./assets/typescript/tree-sitter-typescript.wasm" with { type: "file" }

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        queries: {
          highlights: [resolve(dirname(fileURLToPath(import.meta.url)), javascript_highlights)],
        },
        wasm: resolve(dirname(fileURLToPath(import.meta.url)), javascript_language),
      },
      {
        filetype: "typescript",
        queries: {
          highlights: [resolve(dirname(fileURLToPath(import.meta.url)), typescript_highlights)],
        },
        wasm: resolve(dirname(fileURLToPath(import.meta.url)), typescript_language),
      },
    ]
  }
  return _cachedParsers
}
